[project]
name = 'Blockchain-Based-Liquidity-Mining-Optimization'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.postition-management]
path = 'contracts/postition-management.clar'
clarity_version = 2
epoch = 2.5

[contracts.yeild-projection]
path = 'contracts/yeild-projection.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
